# Generated by Django 4.1.5 on 2023-02-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todopost', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoModel',
        ),
    ]
